### ISSUE TITLE
Property example values involving dictionaries are displayed in HTML using Python syntax

### ISSUE THREAD

**Issue by vaitkus** [Materials-Consortia/optimade-property-tools#2]
For example, see the webpage for the `person` property [1]. The original YAML file provides examples as:
```
examples:
  - {"name": "John Smith"}
  - {"name": "Arthur Dent", "firstname": "Arthur", "lastname": "Dent"}
```
while on the website they are displayed as:
```
    OrderedDict([('name', 'John Smith')])
    OrderedDict([('name', 'Arthur Dent'), ('firstname', 'Arthur'), ('lastname', 'Dent')])
```

This issue was originally noticed in https://github.com/Materials-Consortia/OPTIMADE/pull/445/files#r1533928897.

[1] https://schemas.optimade.org/releases/v1.2.0/v1.2/properties/optimade/common/person

**Comment by ml-evs** [comment]
See #3

**Comment by rartino** [comment]
Fixed by https://github.com/Materials-Consortia/optimade-property-tools/commit/93e4c6f925783f47a51883f4f80965a82a8bf02b ; but I let #3 be open for discussion of merits vs. the merged one.
